name: Deploy Frontend
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: "./.github/workflows/test.yaml"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build client
        run: docker build -t gafalcon/docker-practice-multi-client ./client
      - name: Build nginx
        run: docker build -t gafalcon/docker-practice-multi-nginx ./nginx
      - name: Build server
        run: docker build -t gafalcon/docker-practice-multi-server ./server
      - name: Build worker
        run: docker build -t gafalcon/docker-practice-multi-worker ./workder
      - name: Login docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ DOCKER_ID }}" --password-stdin
      - name: Push images
        run: |
          docker push gafalcon/docker-practice-multi-client
          docker push gafalcon/docker-practice-multi-nginx
          docker push gafalcon/docker-practice-multi-server
          docker push gafalcon/docker-practice-multi-worker
